### ISSUE TITLE
touchable child must either be native or forward setnativeprops to a native component

### ISSUE THREAD

**Issue by xpbtmusic** [knowbody/react-native-text#10]
Hi:
  There is a problem, "react": "16.0.0-alpha.12","react-native": "0.45.1", istouchable child must either be native or forward setnativeprops to a native component

**Comment by rupalpatel0008** [comment]
@xpbtmusic If you want to use ScalableText inside Touchable component, wrap your ScalableText in a view.
E.g.
`
<TouchableHighlight>
  <View>
    <ScalableText style={style.buttonTextStyle}>
      {'ButtonText'}
    </ScalableText>
  </View>
</TouchableHighlight>

`

This is will not give you the issue you have reported.

**Comment by knowbody** [comment]
Hey I tried to reproduce your error but it seems to work fine, here's the link to Snack: https://snack.expo.io/BJV48HSKX

if this is still the issue please reopen it, and provide a reproduction
