### ISSUE TITLE
React native TextInput support

### ISSUE THREAD

**Issue by cocoafuel** [knowbody/react-native-text#16]
Thanks for a great package. 
I wanna use it with textinput component, is there any way possible ?

**Comment by zaguiini** [comment]
@knowbody I think it’s a pertinent issue. Correct me if I’m wrong but I think you can apply the same formula to the placeholder font size

**Comment by zaguiini** [comment]
Maybe export the formula for the font size and people could use it to fix any text anywhere they’d like to?

**Comment by knowbody** [comment]
yup, we could have named exports of the functions that are needed. Feel free to send the PR.

**Comment by zaguiini** [comment]
It's on #17!

**Comment by knowbody** [comment]
Done in #17
