### ISSUE TITLE
Android Tablets

### ISSUE THREAD

**Issue by jacinto123** [knowbody/react-native-text#18]
Using this package has been great on most Android  phones I have tried but it seems like on the android tablets I have tried the text gets way to big. I set a font to 22 and on the tablet it grows to 55 spreading way bigger then its containing box. Is there anything I can do to make it smaller on tablet but stay exactly sexy beautiful on the phones?

**Comment by zaguiini** [comment]
I think there's something to do with the `deviceBaseWidth` prop. Try to set it to something near the tablet width

**Comment by knowbody** [comment]
please check the new 1.0 version and if the problem persists, please file a new issue.
