### ISSUE TITLE
How to give space between the text and text decoration line

### ISSUE THREAD

**Issue by nihp** [knowbody/react-native-text#19]
How to give space between the text and text-decoration line in react-native.

I have set text-decoration line but it not shows space in between the text and decoration line.

Refer this image https://i.stack.imgur.com/6woPN.png

Also, I have set boderBottom width. It shows in the entire screen

https://i.stack.imgur.com/gNNFY.png

Any solution for this?

**Comment by knowbody** [comment]
this is unrelated to this library, I think you are looking for something like https://stackoverflow.com/a/57710879
