### ISSUE TITLE
Android Review?

### ISSUE THREAD

**Issue by shukerullah** [knowbody/react-native-text#7]
Is this Text component work well on Android too?

**Comment by knowbody** [comment]
To be honest I haven't been testing it heavily on Android, I only checked on a few devices. Would love to hear some feedback/issues if you find any.

**Comment by luisfuertes** [comment]
I think it not working on Android (Tested on Xiaomi Mi A2)

**Comment by knowbody** [comment]
@luisfuertes could you please open a new issue and show some screenshots and some small repro code? perhaps on https://snack.expo.io ?
